version: '{build}'

image: Visual Studio 2017

configuration: Release

platform: Any CPU

only_commits:
  files:
    - src/
    - templates/

build_script:

- ps: >-

    $currentPath = Get-Location

    dotnet restore .\AWSLambdaSharpTemplate.sln

    dotnet build .\AWSLambdaSharpTemplate.sln -c Release --no-incremental

    Get-ChildItem .\tests\ -Directory | %{ cd $_.FullName; dotnet test }

    Set-Location $currentPath

    Get-ChildItem src\**\*.csproj -Recurse | % { dotnet pack $_.FullName -c Release  }

    dotnet restore .\templates\Kralizek.Lambda.Templates.csproj

    dotnet pack .\templates\Kralizek.Lambda.Templates.csproj -c Release

test: off

artifacts:

- path: '**\*.nupkg'